/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOreRouteImport } from './routes/_authenticated.ore'
import { Route as AuthenticatedLavoriRouteImport } from './routes/_authenticated.lavori'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated.impostazioni'
import { Route as AuthenticatedGrossistiRouteImport } from './routes/_authenticated.grossisti'
import { Route as AuthenticatedFattureRouteImport } from './routes/_authenticated.fatture'
import { Route as AuthenticatedDicoRouteImport } from './routes/_authenticated.dico'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedContractorsRouteImport } from './routes/_authenticated.contractors'
import { Route as AuthenticatedClientiRouteImport } from './routes/_authenticated.clienti'
import { Route as AuthenticatedAcquistiRouteImport } from './routes/_authenticated.acquisti'
import { Route as AuthenticatedOreStoricoRouteImport } from './routes/_authenticated.ore.storico'
import { Route as AuthenticatedOreApprovazioneRouteImport } from './routes/_authenticated.ore.approvazione'
import { Route as AuthenticatedLavoriIdRouteImport } from './routes/_authenticated.lavori.$id'
import { Route as AuthenticatedFattureIdRouteImport } from './routes/_authenticated.fatture.$id'
import { Route as AuthenticatedDicoIdRouteImport } from './routes/_authenticated.dico.$id'
import { Route as AuthenticatedContractorsIdRouteImport } from './routes/_authenticated.contractors.$id'
import { Route as AuthenticatedClientiIdRouteImport } from './routes/_authenticated.clienti.$id'
import { Route as AuthenticatedAcquistiNuovoRouteImport } from './routes/_authenticated.acquisti.nuovo'
import { Route as AuthenticatedAcquistiIdRouteImport } from './routes/_authenticated.acquisti.$id'
import { Route as AuthenticatedClientiIdLavoriJobIdRouteImport } from './routes/_authenticated.clienti.$id.lavori.$jobId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOreRoute = AuthenticatedOreRouteImport.update({
  id: '/ore',
  path: '/ore',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLavoriRoute = AuthenticatedLavoriRouteImport.update({
  id: '/lavori',
  path: '/lavori',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrossistiRoute = AuthenticatedGrossistiRouteImport.update({
  id: '/grossisti',
  path: '/grossisti',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFattureRoute = AuthenticatedFattureRouteImport.update({
  id: '/fatture',
  path: '/fatture',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDicoRoute = AuthenticatedDicoRouteImport.update({
  id: '/dico',
  path: '/dico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContractorsRoute =
  AuthenticatedContractorsRouteImport.update({
    id: '/contractors',
    path: '/contractors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientiRoute = AuthenticatedClientiRouteImport.update({
  id: '/clienti',
  path: '/clienti',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAcquistiRoute = AuthenticatedAcquistiRouteImport.update({
  id: '/acquisti',
  path: '/acquisti',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOreStoricoRoute = AuthenticatedOreStoricoRouteImport.update({
  id: '/storico',
  path: '/storico',
  getParentRoute: () => AuthenticatedOreRoute,
} as any)
const AuthenticatedOreApprovazioneRoute =
  AuthenticatedOreApprovazioneRouteImport.update({
    id: '/approvazione',
    path: '/approvazione',
    getParentRoute: () => AuthenticatedOreRoute,
  } as any)
const AuthenticatedLavoriIdRoute = AuthenticatedLavoriIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedLavoriRoute,
} as any)
const AuthenticatedFattureIdRoute = AuthenticatedFattureIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedFattureRoute,
} as any)
const AuthenticatedDicoIdRoute = AuthenticatedDicoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDicoRoute,
} as any)
const AuthenticatedContractorsIdRoute =
  AuthenticatedContractorsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedContractorsRoute,
  } as any)
const AuthenticatedClientiIdRoute = AuthenticatedClientiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientiRoute,
} as any)
const AuthenticatedAcquistiNuovoRoute =
  AuthenticatedAcquistiNuovoRouteImport.update({
    id: '/nuovo',
    path: '/nuovo',
    getParentRoute: () => AuthenticatedAcquistiRoute,
  } as any)
const AuthenticatedAcquistiIdRoute = AuthenticatedAcquistiIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAcquistiRoute,
} as any)
const AuthenticatedClientiIdLavoriJobIdRoute =
  AuthenticatedClientiIdLavoriJobIdRouteImport.update({
    id: '/lavori/$jobId',
    path: '/lavori/$jobId',
    getParentRoute: () => AuthenticatedClientiIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/acquisti': typeof AuthenticatedAcquistiRouteWithChildren
  '/clienti': typeof AuthenticatedClientiRouteWithChildren
  '/contractors': typeof AuthenticatedContractorsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dico': typeof AuthenticatedDicoRouteWithChildren
  '/fatture': typeof AuthenticatedFattureRouteWithChildren
  '/grossisti': typeof AuthenticatedGrossistiRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/lavori': typeof AuthenticatedLavoriRouteWithChildren
  '/ore': typeof AuthenticatedOreRouteWithChildren
  '/acquisti/$id': typeof AuthenticatedAcquistiIdRoute
  '/acquisti/nuovo': typeof AuthenticatedAcquistiNuovoRoute
  '/clienti/$id': typeof AuthenticatedClientiIdRouteWithChildren
  '/contractors/$id': typeof AuthenticatedContractorsIdRoute
  '/dico/$id': typeof AuthenticatedDicoIdRoute
  '/fatture/$id': typeof AuthenticatedFattureIdRoute
  '/lavori/$id': typeof AuthenticatedLavoriIdRoute
  '/ore/approvazione': typeof AuthenticatedOreApprovazioneRoute
  '/ore/storico': typeof AuthenticatedOreStoricoRoute
  '/clienti/$id/lavori/$jobId': typeof AuthenticatedClientiIdLavoriJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/acquisti': typeof AuthenticatedAcquistiRouteWithChildren
  '/clienti': typeof AuthenticatedClientiRouteWithChildren
  '/contractors': typeof AuthenticatedContractorsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dico': typeof AuthenticatedDicoRouteWithChildren
  '/fatture': typeof AuthenticatedFattureRouteWithChildren
  '/grossisti': typeof AuthenticatedGrossistiRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/lavori': typeof AuthenticatedLavoriRouteWithChildren
  '/ore': typeof AuthenticatedOreRouteWithChildren
  '/acquisti/$id': typeof AuthenticatedAcquistiIdRoute
  '/acquisti/nuovo': typeof AuthenticatedAcquistiNuovoRoute
  '/clienti/$id': typeof AuthenticatedClientiIdRouteWithChildren
  '/contractors/$id': typeof AuthenticatedContractorsIdRoute
  '/dico/$id': typeof AuthenticatedDicoIdRoute
  '/fatture/$id': typeof AuthenticatedFattureIdRoute
  '/lavori/$id': typeof AuthenticatedLavoriIdRoute
  '/ore/approvazione': typeof AuthenticatedOreApprovazioneRoute
  '/ore/storico': typeof AuthenticatedOreStoricoRoute
  '/clienti/$id/lavori/$jobId': typeof AuthenticatedClientiIdLavoriJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/acquisti': typeof AuthenticatedAcquistiRouteWithChildren
  '/_authenticated/clienti': typeof AuthenticatedClientiRouteWithChildren
  '/_authenticated/contractors': typeof AuthenticatedContractorsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dico': typeof AuthenticatedDicoRouteWithChildren
  '/_authenticated/fatture': typeof AuthenticatedFattureRouteWithChildren
  '/_authenticated/grossisti': typeof AuthenticatedGrossistiRoute
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/_authenticated/lavori': typeof AuthenticatedLavoriRouteWithChildren
  '/_authenticated/ore': typeof AuthenticatedOreRouteWithChildren
  '/_authenticated/acquisti/$id': typeof AuthenticatedAcquistiIdRoute
  '/_authenticated/acquisti/nuovo': typeof AuthenticatedAcquistiNuovoRoute
  '/_authenticated/clienti/$id': typeof AuthenticatedClientiIdRouteWithChildren
  '/_authenticated/contractors/$id': typeof AuthenticatedContractorsIdRoute
  '/_authenticated/dico/$id': typeof AuthenticatedDicoIdRoute
  '/_authenticated/fatture/$id': typeof AuthenticatedFattureIdRoute
  '/_authenticated/lavori/$id': typeof AuthenticatedLavoriIdRoute
  '/_authenticated/ore/approvazione': typeof AuthenticatedOreApprovazioneRoute
  '/_authenticated/ore/storico': typeof AuthenticatedOreStoricoRoute
  '/_authenticated/clienti/$id/lavori/$jobId': typeof AuthenticatedClientiIdLavoriJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/acquisti'
    | '/clienti'
    | '/contractors'
    | '/dashboard'
    | '/dico'
    | '/fatture'
    | '/grossisti'
    | '/impostazioni'
    | '/lavori'
    | '/ore'
    | '/acquisti/$id'
    | '/acquisti/nuovo'
    | '/clienti/$id'
    | '/contractors/$id'
    | '/dico/$id'
    | '/fatture/$id'
    | '/lavori/$id'
    | '/ore/approvazione'
    | '/ore/storico'
    | '/clienti/$id/lavori/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/acquisti'
    | '/clienti'
    | '/contractors'
    | '/dashboard'
    | '/dico'
    | '/fatture'
    | '/grossisti'
    | '/impostazioni'
    | '/lavori'
    | '/ore'
    | '/acquisti/$id'
    | '/acquisti/nuovo'
    | '/clienti/$id'
    | '/contractors/$id'
    | '/dico/$id'
    | '/fatture/$id'
    | '/lavori/$id'
    | '/ore/approvazione'
    | '/ore/storico'
    | '/clienti/$id/lavori/$jobId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/acquisti'
    | '/_authenticated/clienti'
    | '/_authenticated/contractors'
    | '/_authenticated/dashboard'
    | '/_authenticated/dico'
    | '/_authenticated/fatture'
    | '/_authenticated/grossisti'
    | '/_authenticated/impostazioni'
    | '/_authenticated/lavori'
    | '/_authenticated/ore'
    | '/_authenticated/acquisti/$id'
    | '/_authenticated/acquisti/nuovo'
    | '/_authenticated/clienti/$id'
    | '/_authenticated/contractors/$id'
    | '/_authenticated/dico/$id'
    | '/_authenticated/fatture/$id'
    | '/_authenticated/lavori/$id'
    | '/_authenticated/ore/approvazione'
    | '/_authenticated/ore/storico'
    | '/_authenticated/clienti/$id/lavori/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ore': {
      id: '/_authenticated/ore'
      path: '/ore'
      fullPath: '/ore'
      preLoaderRoute: typeof AuthenticatedOreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lavori': {
      id: '/_authenticated/lavori'
      path: '/lavori'
      fullPath: '/lavori'
      preLoaderRoute: typeof AuthenticatedLavoriRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grossisti': {
      id: '/_authenticated/grossisti'
      path: '/grossisti'
      fullPath: '/grossisti'
      preLoaderRoute: typeof AuthenticatedGrossistiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fatture': {
      id: '/_authenticated/fatture'
      path: '/fatture'
      fullPath: '/fatture'
      preLoaderRoute: typeof AuthenticatedFattureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dico': {
      id: '/_authenticated/dico'
      path: '/dico'
      fullPath: '/dico'
      preLoaderRoute: typeof AuthenticatedDicoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contractors': {
      id: '/_authenticated/contractors'
      path: '/contractors'
      fullPath: '/contractors'
      preLoaderRoute: typeof AuthenticatedContractorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clienti': {
      id: '/_authenticated/clienti'
      path: '/clienti'
      fullPath: '/clienti'
      preLoaderRoute: typeof AuthenticatedClientiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acquisti': {
      id: '/_authenticated/acquisti'
      path: '/acquisti'
      fullPath: '/acquisti'
      preLoaderRoute: typeof AuthenticatedAcquistiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ore/storico': {
      id: '/_authenticated/ore/storico'
      path: '/storico'
      fullPath: '/ore/storico'
      preLoaderRoute: typeof AuthenticatedOreStoricoRouteImport
      parentRoute: typeof AuthenticatedOreRoute
    }
    '/_authenticated/ore/approvazione': {
      id: '/_authenticated/ore/approvazione'
      path: '/approvazione'
      fullPath: '/ore/approvazione'
      preLoaderRoute: typeof AuthenticatedOreApprovazioneRouteImport
      parentRoute: typeof AuthenticatedOreRoute
    }
    '/_authenticated/lavori/$id': {
      id: '/_authenticated/lavori/$id'
      path: '/$id'
      fullPath: '/lavori/$id'
      preLoaderRoute: typeof AuthenticatedLavoriIdRouteImport
      parentRoute: typeof AuthenticatedLavoriRoute
    }
    '/_authenticated/fatture/$id': {
      id: '/_authenticated/fatture/$id'
      path: '/$id'
      fullPath: '/fatture/$id'
      preLoaderRoute: typeof AuthenticatedFattureIdRouteImport
      parentRoute: typeof AuthenticatedFattureRoute
    }
    '/_authenticated/dico/$id': {
      id: '/_authenticated/dico/$id'
      path: '/$id'
      fullPath: '/dico/$id'
      preLoaderRoute: typeof AuthenticatedDicoIdRouteImport
      parentRoute: typeof AuthenticatedDicoRoute
    }
    '/_authenticated/contractors/$id': {
      id: '/_authenticated/contractors/$id'
      path: '/$id'
      fullPath: '/contractors/$id'
      preLoaderRoute: typeof AuthenticatedContractorsIdRouteImport
      parentRoute: typeof AuthenticatedContractorsRoute
    }
    '/_authenticated/clienti/$id': {
      id: '/_authenticated/clienti/$id'
      path: '/$id'
      fullPath: '/clienti/$id'
      preLoaderRoute: typeof AuthenticatedClientiIdRouteImport
      parentRoute: typeof AuthenticatedClientiRoute
    }
    '/_authenticated/acquisti/nuovo': {
      id: '/_authenticated/acquisti/nuovo'
      path: '/nuovo'
      fullPath: '/acquisti/nuovo'
      preLoaderRoute: typeof AuthenticatedAcquistiNuovoRouteImport
      parentRoute: typeof AuthenticatedAcquistiRoute
    }
    '/_authenticated/acquisti/$id': {
      id: '/_authenticated/acquisti/$id'
      path: '/$id'
      fullPath: '/acquisti/$id'
      preLoaderRoute: typeof AuthenticatedAcquistiIdRouteImport
      parentRoute: typeof AuthenticatedAcquistiRoute
    }
    '/_authenticated/clienti/$id/lavori/$jobId': {
      id: '/_authenticated/clienti/$id/lavori/$jobId'
      path: '/lavori/$jobId'
      fullPath: '/clienti/$id/lavori/$jobId'
      preLoaderRoute: typeof AuthenticatedClientiIdLavoriJobIdRouteImport
      parentRoute: typeof AuthenticatedClientiIdRoute
    }
  }
}

interface AuthenticatedAcquistiRouteChildren {
  AuthenticatedAcquistiIdRoute: typeof AuthenticatedAcquistiIdRoute
  AuthenticatedAcquistiNuovoRoute: typeof AuthenticatedAcquistiNuovoRoute
}

const AuthenticatedAcquistiRouteChildren: AuthenticatedAcquistiRouteChildren = {
  AuthenticatedAcquistiIdRoute: AuthenticatedAcquistiIdRoute,
  AuthenticatedAcquistiNuovoRoute: AuthenticatedAcquistiNuovoRoute,
}

const AuthenticatedAcquistiRouteWithChildren =
  AuthenticatedAcquistiRoute._addFileChildren(
    AuthenticatedAcquistiRouteChildren,
  )

interface AuthenticatedClientiIdRouteChildren {
  AuthenticatedClientiIdLavoriJobIdRoute: typeof AuthenticatedClientiIdLavoriJobIdRoute
}

const AuthenticatedClientiIdRouteChildren: AuthenticatedClientiIdRouteChildren =
  {
    AuthenticatedClientiIdLavoriJobIdRoute:
      AuthenticatedClientiIdLavoriJobIdRoute,
  }

const AuthenticatedClientiIdRouteWithChildren =
  AuthenticatedClientiIdRoute._addFileChildren(
    AuthenticatedClientiIdRouteChildren,
  )

interface AuthenticatedClientiRouteChildren {
  AuthenticatedClientiIdRoute: typeof AuthenticatedClientiIdRouteWithChildren
}

const AuthenticatedClientiRouteChildren: AuthenticatedClientiRouteChildren = {
  AuthenticatedClientiIdRoute: AuthenticatedClientiIdRouteWithChildren,
}

const AuthenticatedClientiRouteWithChildren =
  AuthenticatedClientiRoute._addFileChildren(AuthenticatedClientiRouteChildren)

interface AuthenticatedContractorsRouteChildren {
  AuthenticatedContractorsIdRoute: typeof AuthenticatedContractorsIdRoute
}

const AuthenticatedContractorsRouteChildren: AuthenticatedContractorsRouteChildren =
  {
    AuthenticatedContractorsIdRoute: AuthenticatedContractorsIdRoute,
  }

const AuthenticatedContractorsRouteWithChildren =
  AuthenticatedContractorsRoute._addFileChildren(
    AuthenticatedContractorsRouteChildren,
  )

interface AuthenticatedDicoRouteChildren {
  AuthenticatedDicoIdRoute: typeof AuthenticatedDicoIdRoute
}

const AuthenticatedDicoRouteChildren: AuthenticatedDicoRouteChildren = {
  AuthenticatedDicoIdRoute: AuthenticatedDicoIdRoute,
}

const AuthenticatedDicoRouteWithChildren =
  AuthenticatedDicoRoute._addFileChildren(AuthenticatedDicoRouteChildren)

interface AuthenticatedFattureRouteChildren {
  AuthenticatedFattureIdRoute: typeof AuthenticatedFattureIdRoute
}

const AuthenticatedFattureRouteChildren: AuthenticatedFattureRouteChildren = {
  AuthenticatedFattureIdRoute: AuthenticatedFattureIdRoute,
}

const AuthenticatedFattureRouteWithChildren =
  AuthenticatedFattureRoute._addFileChildren(AuthenticatedFattureRouteChildren)

interface AuthenticatedLavoriRouteChildren {
  AuthenticatedLavoriIdRoute: typeof AuthenticatedLavoriIdRoute
}

const AuthenticatedLavoriRouteChildren: AuthenticatedLavoriRouteChildren = {
  AuthenticatedLavoriIdRoute: AuthenticatedLavoriIdRoute,
}

const AuthenticatedLavoriRouteWithChildren =
  AuthenticatedLavoriRoute._addFileChildren(AuthenticatedLavoriRouteChildren)

interface AuthenticatedOreRouteChildren {
  AuthenticatedOreApprovazioneRoute: typeof AuthenticatedOreApprovazioneRoute
  AuthenticatedOreStoricoRoute: typeof AuthenticatedOreStoricoRoute
}

const AuthenticatedOreRouteChildren: AuthenticatedOreRouteChildren = {
  AuthenticatedOreApprovazioneRoute: AuthenticatedOreApprovazioneRoute,
  AuthenticatedOreStoricoRoute: AuthenticatedOreStoricoRoute,
}

const AuthenticatedOreRouteWithChildren =
  AuthenticatedOreRoute._addFileChildren(AuthenticatedOreRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAcquistiRoute: typeof AuthenticatedAcquistiRouteWithChildren
  AuthenticatedClientiRoute: typeof AuthenticatedClientiRouteWithChildren
  AuthenticatedContractorsRoute: typeof AuthenticatedContractorsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDicoRoute: typeof AuthenticatedDicoRouteWithChildren
  AuthenticatedFattureRoute: typeof AuthenticatedFattureRouteWithChildren
  AuthenticatedGrossistiRoute: typeof AuthenticatedGrossistiRoute
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRoute
  AuthenticatedLavoriRoute: typeof AuthenticatedLavoriRouteWithChildren
  AuthenticatedOreRoute: typeof AuthenticatedOreRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcquistiRoute: AuthenticatedAcquistiRouteWithChildren,
  AuthenticatedClientiRoute: AuthenticatedClientiRouteWithChildren,
  AuthenticatedContractorsRoute: AuthenticatedContractorsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDicoRoute: AuthenticatedDicoRouteWithChildren,
  AuthenticatedFattureRoute: AuthenticatedFattureRouteWithChildren,
  AuthenticatedGrossistiRoute: AuthenticatedGrossistiRoute,
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRoute,
  AuthenticatedLavoriRoute: AuthenticatedLavoriRouteWithChildren,
  AuthenticatedOreRoute: AuthenticatedOreRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
